# Generated by Django 5.0.7 on 2024-07-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('sur_name', models.CharField(max_length=255)),
                ('other_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('tribe', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('residence', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('home_address', models.CharField(max_length=255)),
                ('chair_person', models.CharField(max_length=255)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('work_place', models.CharField(max_length=255)),
                ('work', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
