# Generated by Django 5.0.7 on 2024-07-24 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0002_rename_guarantor_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(max_length=255)),
                ('amount_in_bank', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microfinance.client')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gari', 'Gari'), ('hati', 'Hati'), ('others', 'Others')], default='others', max_length=10)),
                ('custom_guarantee', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='guarantee_files/')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='microfinance.loan')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gari', 'Gari'), ('hati', 'Hati'), ('others', 'Others')], default='others', max_length=10)),
                ('custom_guarantee', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='alternative_guarantee_files/')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_guarantees', to='microfinance.loan')),
            ],
        ),
    ]
