# Generated by Django 5.0.7 on 2024-07-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0003_loan_guarantee_alternativeguarantee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativeguarantee',
            name='custom_guarantee',
        ),
        migrations.RemoveField(
            model_name='alternativeguarantee',
            name='type',
        ),
        migrations.RemoveField(
            model_name='guarantee',
            name='custom_guarantee',
        ),
        migrations.RemoveField(
            model_name='guarantee',
            name='type',
        ),
        migrations.AddField(
            model_name='alternativeguarantee',
            name='alternative_guarantee_type',
            field=models.CharField(choices=[('gari', 'Gari'), ('hati', 'Hati'), ('others', 'Others')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alternativeguarantee',
            name='custom_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='custom_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='guarantee_type',
            field=models.CharField(choices=[('gari', 'Gari'), ('hati', 'Hati'), ('others', 'Others')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
