# Generated by Django 5.0.7 on 2024-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0004_remove_alternativeguarantee_custom_guarantee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativeguarantee',
            name='alternative_guarantee_type',
        ),
        migrations.RemoveField(
            model_name='alternativeguarantee',
            name='custom_description',
        ),
        migrations.RemoveField(
            model_name='guarantee',
            name='custom_description',
        ),
        migrations.RemoveField(
            model_name='guarantee',
            name='guarantee_type',
        ),
        migrations.AddField(
            model_name='alternativeguarantee',
            name='custom_guarantee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alternativeguarantee',
            name='type',
            field=models.CharField(choices=[('gari', 'Gari'), ('hati', 'Hati'), ('others', 'Others')], default='others', max_length=10),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='custom_guarantee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='type',
            field=models.CharField(choices=[('gari', 'Gari'), ('hati', 'Hati'), ('others', 'Others')], default='others', max_length=10),
        ),
    ]
