# Generated by Django 5.0.7 on 2024-07-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0007_remove_guarantor_phone3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativeguarantee',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='%(class)s_files/'),
        ),
        migrations.AlterField(
            model_name='alternativeguarantee',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='microfinance.loan'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='%(class)s_files/'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='microfinance.loan'),
        ),
    ]
