# Generated by Django 5.0.7 on 2024-07-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0008_alter_alternativeguarantee_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantee',
            name='loan',
        ),
        migrations.AddField(
            model_name='loan',
            name='altAttachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='altGuarantee',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantee',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AlternativeGuarantee',
        ),
        migrations.DeleteModel(
            name='Guarantee',
        ),
    ]
