# Generated by Django 5.0.7 on 2024-07-28 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0009_remove_guarantee_loan_loan_altattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='loan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='microfinance.loan'),
            preserve_default=False,
        ),
    ]
