# Generated by Django 5.0.7 on 2024-08-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0010_guarantor_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
