# Generated by Django 5.0.7 on 2024-08-03 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0011_loan_created_alter_loan_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='created',
        ),
        migrations.AddField(
            model_name='loan',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
