# Generated by Django 5.0.7 on 2024-08-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0012_remove_loan_created_loan_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='date_created',
            new_name='date',
        ),
    ]
