# Generated by Django 5.0.7 on 2024-08-03 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0013_rename_date_created_loan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='microfinance.client'),
        ),
    ]
